list(APPEND SRC 
  ${CMAKE_CURRENT_LIST_DIR}/WindowFunction.h
  ${CMAKE_CURRENT_LIST_DIR}/Ooura_FFT.h
  ${CMAKE_CURRENT_LIST_DIR}/OA.h
  ${CMAKE_CURRENT_LIST_DIR}/STFT.h
  ${CMAKE_CURRENT_LIST_DIR}/DFT.h
  ${CMAKE_CURRENT_LIST_DIR}/FFT.h
  
	)
list(APPEND INCL
	${CMAKE_CURRENT_LIST_DIR}
)