list(APPEND SRC 
  ${CMAKE_CURRENT_LIST_DIR}/HannWindow.h
  ${CMAKE_CURRENT_LIST_DIR}/Ooura_FFT.h
  ${CMAKE_CURRENT_LIST_DIR}/OA.h
  ${CMAKE_CURRENT_LIST_DIR}/STFT.h
	)
list(APPEND INCL
	${CMAKE_CURRENT_LIST_DIR}
)